services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - ./sonarr:/config
      - ${MEDIA_DOWNLOADS_DIR}:/downloads
      - ${MEDIA_TV_SERIES_DIR}:/tv
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - ./radarr:/config
      - ${MEDIA_DOWNLOADS_DIR}:/downloads
      - ${MEDIA_MOVIES_DIR}:/movies
    ports:
      - 7878:7878
    restart: unless-stopped
  overseerr:
    image: linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - ./overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped
