services:
  nzbget:
    image: linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      - NZBGET_USER=${NZBGET_USER}
      - NZBGET_PASS=${NZBGET_PASS}
    volumes:
      - ./nzbget:/config
      - /home/chris/vault/Plex:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - ./sonarr:/config
      - /home/chris/vault/Plex/Series:/downloads
      - /home/chris/vault/Plex/tv:/tv
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - ./radarr:/config
      - /home/chris/vault/Plex/Movies:/downloads
      - /home/chris/vault/Plex/Movies:/movies
    ports:
      - 7878:7878
    restart: unless-stopped

  overseerr:
    image: linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - ./overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      - WEBUI_PORT=8085
      - WEBUI_USERNAME=${QBT_WEBUI_USERNAME}
      - WEBUI_PASSWORD=${QBT_WEBUI_PASSWORD}
    volumes:
      - ./qbittorrent:/config
      - /home/chris/vault/Plex:/downloads
    ports:
      - 8085:8085
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
