services:
  qbittorrent:
    image: linuxserver/qbittorrent:4.6.5
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      - WEBUI_PORT=8085
    volumes:
      - ${QBT_CONFIG_DIR-./qbittorrent}:/config
      - ${QBT_DOWNLOAD_DIR-./../shared/downloads}:/downloads
    restart: unless-stopped
    network_mode: "service:gluetun-media"
    depends_on:
      - gluetun-media
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - ${PROWLARR_CONFIG_DIR-./prowlarr/config}:/config
    restart: unless-stopped
    network_mode: "service:gluetun-media"
    depends_on:
      - gluetun-media
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - ${SONARR_CONFIG_DIR-./sonarr/config}:/config
      - ${SONARR_DOWNLOADS_DIR-./../shared/downloads}:/downloads
      - ${SONARR_TV_SERIES_DIR-./../shared/Series}:/tv
    restart: unless-stopped
    network_mode: "service:gluetun-media"
    depends_on:
      - gluetun-media
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - ${RADARR_CONFIG_DIR-./radarr/config}:/config
      - ${RADARR_DOWNLOADS_DIR-./../shared/downloads}:/downloads
      - ${RADARR_MOVIES_DIR-./../shared/Movies}:/movies
    restart: unless-stopped
    network_mode: "service:gluetun-media"
    depends_on:
      - gluetun-media
  overseerr:
    image: linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - ${OVERSEERR_CONFIG_DIR-./overseer/config}:/config
    restart: unless-stopped
    network_mode: "service:gluetun-media"
    depends_on:
      - gluetun-media
  gluetun-media:
    image: qmcgaw/gluetun
    container_name: gluetun-media
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8085:8085 # qBittorrent
      - 6881:6881 # qBittorrent
      - 6881:6881/udp # qBittorrent
      - 9696:9696 # Prowlarr
      - 8989:8989 # Sonarr
      - 7878:7878 # Radarr
      - 5055:5055 # Overseerr
    volumes:
      - ./gluetun:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=${GLUETUN_VPN_ENDPOINT_IP}
      - VPN_ENDPOINT_PORT=${GLUETUN_VPN_ENDPOINT_PORT}
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
      - WIREGUARD_PUBLIC_KEY=${GLUETUN_WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${GLUETUN_WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${GLUETUN_WIREGUARD_ADDRESSES}
      - FIREWALL_OUTBOUND_SUBNETS=${GLUETUN_FIREWALL_OUTBOUND_SUBNETS}
      - VPN_PORT_FORWARDING=on
      # Timezone for accurate log times
      - TZ=Asia/Manila
