services:
  trilium:
    image: zadam/trilium
    restart: always
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    ports:
      - ${TRILIUM_PORT:-8080}:8080
    volumes:
      - ${TRILIUM_DATA_DIR:-./trilium-data}:/home/node/trilium-data
  trilium-cf-tunnel:
    container_name: trilium-cf-tunnel
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${TRILIUM_CF_TUNNEL_TOKEN}
    restart: unless-stopped
    network_mode: host
    profiles:
      - cloudflare
