services:
  qbittorrent:
    image: linuxserver/qbittorrent:4.6.0
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      - WEBUI_PORT=8085
    volumes:
      - ${QBT_CONFIG_DIR-./qbittorrent}:/config
      - ${QBT_DOWNLOAD_DIR-./../shared/downloads}:/downloads
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun

  qbittorrent-cf-tunnel:
    container_name: qbittorrent-cf-tunnel
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${QBT_CF_TUNNEL_TOKEN}
    restart: unless-stopped
    network_mode: host
    profiles:
      - cloudflare

  nzbget:
    image: linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      - NZBGET_USER=${NZBGET_USER}
      - NZBGET_PASS=${NZBGET_PASS}
    volumes:
      - ${NZBGET_CONFIG_DIR-./nzbget}:/config
      - ${NZBGET_DOWNLOAD_DIR-./../shared/downloads}:/downloads
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun

  nzbget-cf-tunnel:
    container_name: nzbget-cf-tunnel
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${NZBGET_CF_TUNNEL_TOKEN}
    restart: unless-stopped
    network_mode: host
    profiles:
      - cloudflare

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8085:8085 # qBittorrent
      - 6881:6881 # qBittorrent
      - 6881:6881/udp # qBittorrent
      - 6789:6789 # NZBGet
    volumes:
      - ./gluetun:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=privatevpn
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER=${GLUETUN_OPENVPN_USER}
      - OPENVPN_PASSWORD=${GLUETUN_OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${GLUETUN_SERVER_COUNTRIES}
      # Wireguard:
      #- WIREGUARD_PRIVATE_KEY=${GLUETUN_WIREGUARD_PRIVATE_KEY}
      #- WIREGUARD_ADDRESSES=${GLUETUN_WIREGUARD_ADDRESSES}
      # Timezone for accurate log times
      - TZ=Asia/Manila
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=24h
