services:
  minio:
    image: minio/minio
    ports:
      - "${MINIO_API_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - ${MINIO_DATA_DIRECTORY:-./minio-data}:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":${MINIO_CONSOLE_PORT:-9001}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${MINIO_API_PORT:-9000}/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-cf-tunnel:
    container_name: minio-cf-tunnel
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${MINIO_CF_TUNNEL_TOKEN}
    restart: unless-stopped
    network_mode: host
    profiles:
      - cloudflare
